### PR TITLE
Add breakout dqn example

### PR DESCRIPTION
**Pull request by yngtodd**
Example script for DQN playing Breakout. Following this example-config: https://github.com/MillionIntegrals/vel/blob/master/examples-configs/rl/atari/dqn/breakout_dqn_raw.yaml

### CODE REVIEW

**Comment by yngtodd** [comment]
This example doesn't quite work yet. Still working out the kinks. Right now I am running into this guy:
```
Traceback (most recent call last):
  File "breakout_dqn.py", line 117, in <module>
    breakout_dqn()
  File "breakout_dqn.py", line 111, in breakout_dqn
    reinforcer.train_epoch(epoch_info)
  File "/home/ygx/dev/nykyinen/vel/vel/rl/reinforcers/buffered_single_off_policy_iteration_reinforcer.py", line 78, in train_epoch
    self.train_batch(batch_info)
  File "/home/ygx/dev/nykyinen/vel/vel/rl/reinforcers/buffered_single_off_policy_iteration_reinforcer.py", line 104, in train_batch
    rollout = self.env_roller.rollout(batch_info, self.model)
  File "/home/ygx/dev/kassa/anaconda3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 46, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/ygx/dev/nykyinen/vel/vel/rl/env_roller/single/deque_replay_roller_epsgreedy.py", line 62, in rollout
    ], axis=-1)
ValueError: all the input arrays must have same number of dimensions
```

**Comment by MillionIntegrals** [comment]
The thing about current EnvRoller used for DQN training is that it uses a single environment rather than a `VecEnv` vectorized environment. It would be possible to change the code to use a VecEnv and I plan to do it some day, but in the Nature publication DeepMind team was using just a single env that was rolled out into the replay buffer.

Instead creating a `vec_env` you need to create just a simple env:

```python
    env = ClassicAtariEnv('BreakoutNoFrameskip-v4').instantiate(seed=seed)
```

**Comment by yngtodd** [comment]
Tested and everything is good now! Thanks for the heads up on the `VecEnv`. 

Out of curiosity, is there a particular part of the DQN that makes using `VecEnv` tricky?

**Comment by MillionIntegrals** [comment]
There is no real trickiness involved, it would just require to write a bit of extra code, mostly for sampling from a slightly modified replay buffer and then reinforcer would need to be slightly adjusted to use that.

Replay buffer for VecEnv is already done, because I'm using it for ACER, but currently is has slightly different sampling than needs to be used for DQN.

So yeah, not a hard thing to do in any way, but required few minor adjustments, and I just went on to work on other things.

Naturally, training of DQN and DDPG would get significantly faster with that change.

**Comment by yngtodd** [comment]
Interesting. I just put together an ACER example based on the yaml scripts. Maybe I can play around with creating a VecEnv for the DQN.

**Comment by MillionIntegrals** [comment]
That would be great! Let's chat about it on gitter when you have time.

**Comment by MillionIntegrals** [comment]
Hi, don't know if you're still looking into that but I've been working for some time on version 0.3 of this repository and that would be a large refactor that includes the changes we've been discussing here. I'll close this one for now.

**Pull request closed without merging**
